defaults: &defaults
  adapter: redis
  url: redis://user:online_game@localhost:6379/0

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  url: redis://localhost:6379/0
